require("core.plugin_config.gruvbox")
require("core.plugin_config.catppuccin")
require("core.plugin_config.onedark")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-web-devicons")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.indent-blankline")

